# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details
version: 2

build:
  os: ubuntu-22.04
  tools:
    nodejs: "18"
  commands:
    - node -e "const fs = require('fs'); fs.writeFileSync('README.md', fs.readFileSync('README.md', 'utf8').split(String.fromCharCode(10)).filter(l => !l.includes('Documentation Status')).join(String.fromCharCode(10)));"
    - npm install --global yarn
    - yarn install
    - yarn docs
    - mkdir --parents _readthedocs/html/
    - cp --recursive docs/html/* _readthedocs/html/
