# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details
version: 2

build:
  os: ubuntu-22.04
  tools:
    nodejs: "18"
  commands:
    - python3 -c "lines = open('README.md').readlines(); open('README.md', 'w').writelines([l for l in lines if 'Documentation Status' not in l])"
    - npm install --global yarn
    - yarn install
    - yarn docs
    - mkdir --parents _readthedocs/html/
    - cp --recursive docs/html/* _readthedocs/html/
