import { CostModel } from './CostModel';
import { DelegateRepresentativeThresholds } from './DelegateRepresentativeThresholds';
import { ExUnits } from './ExUnits';
import { ExUnitsPrices } from './ExUnitsPrices';
import { PoolVotingThresholds } from './PoolVotingThresholds';
import { ProtocolVersion } from './ProtocolVersion';
import { UnitInterval } from './UnitInterval';

export interface ProtocolParameters {
  minFeeA: number;
  minFeeB: number;
  maxBlockBodySize: number;
  maxTxSize: number;
  maxBlockHeaderSize: number;
  keyDeposit: number;
  poolDeposit: number;
  maxEpoch: number;
  nOpt: number;
  poolPledgeInfluence: UnitInterval;
  treasuryGrowthRate: UnitInterval;
  expansionRate: UnitInterval;
  decentralisationParam: UnitInterval;
  extraEntropy: string | null;
  protocolVersion: ProtocolVersion;
  minPoolCost: number;
  adaPerUtxoByte: number;
  costModels: CostModel[];
  executionCosts: ExUnitsPrices;
  maxTxExUnits: ExUnits;
  maxBlockExUnits: ExUnits;
  maxValueSize: number;
  collateralPercent: number;
  maxCollateralInputs: number;
  poolVotingThresholds: PoolVotingThresholds;
  drepVotingThresholds: DelegateRepresentativeThresholds;
  minCommitteeSize: number;
  committeeTermLimit: number;
  governanceActionValidityPeriod: number;
  governanceActionDeposit: number;
  drepDeposit: number;
  drepInactivityPeriod: number;
  refScriptCostPerByte: UnitInterval;
}
